#!/usr/bin/env python3
"""Regenerate cloud-config.yaml from nubor-ssh-agent + the systemd unit.

cloud-config.yaml embeds both files verbatim, so editing either one by hand and
forgetting this leaves an image that installs a stale agent. Run it after any
change to those two files:  python guest/build-cloud-config.py
"""

import base64
import pathlib
import textwrap

HERE = pathlib.Path(__file__).parent
HEADER = """#cloud-config
# GENERATED by build-cloud-config.py - edit nubor-ssh-agent / the .service file.
#
# Bake this into an image (packer/diskimage-builder), or pass it to one instance:
#   openstack server create --user-data guest/cloud-config.yaml ...
#
# Then mark the image so nubor knows injection will work:
#   openstack image set --property nubor_agent=true --property os_admin_user=ubuntu <image>
write_files:
  - path: /usr/local/bin/nubor-ssh-agent
    permissions: '0755'
    owner: root:root
    encoding: b64
    content: |
{agent}
  - path: /etc/systemd/system/nubor-ssh-agent.service
    permissions: '0644'
    owner: root:root
    content: |
{service}
runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, enable, --now, nubor-ssh-agent]
"""

agent = HERE.joinpath("nubor-ssh-agent").read_bytes().replace(b"\r\n", b"\n")
service = HERE.joinpath("nubor-ssh-agent.service").read_text().replace("\r\n", "\n")

body = HEADER.format(
    agent=textwrap.indent("\n".join(textwrap.wrap(base64.b64encode(agent).decode(), 76)), " " * 6),
    service=textwrap.indent(service.rstrip("\n"), " " * 6),
)
HERE.joinpath("cloud-config.yaml").write_text(body, newline="\n")
print("wrote cloud-config.yaml")

# The terraform compute module vendors a copy of this file (terraform cannot
# reach across repos at plan time). Refresh it here rather than trusting anyone
# to remember there are two copies.
VENDORED = (
    HERE.parent.parent
    / "terraform-openstack-compute"
    / "files"
    / "nubor-ssh-agent.cloud-config.yaml"
)
if VENDORED.parent.is_dir():
    VENDORED.write_text(body, newline="\n")
    print(f"wrote {VENDORED}")
